<?php
namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Condition;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Cache lookups
        $brands = Brand::pluck('id', 'slug');
        $categories = Category::pluck('id', 'slug');
        $conditions = Condition::pluck('id', 'slug');

        // Image paths
        $laptopUltrabook = '/assets/laptop-ultrabook-C5nU_6_f.jpg';
        $laptopGaming = '/assets/laptop-gaming-CRMi9E0Q.jpg';
        $laptopBusiness = '/assets/laptop-business-3Mb6HsAh.jpg';
        $laptopPreowned = '/assets/laptop-preowned-CnekQJTH.jpg';
        $accBag = '/assets/acc-bag-DUSyzYyb.jpg';
        $accMouse = '/assets/acc-mouse-BbNzBi1z.jpg';
        $accKeyboard = '/assets/acc-keyboard-C2O0-ufI.jpg';
        $accRam = '/assets/acc-ram-bHl5zo9i.jpg';
        $accHeadphone = '/assets/acc-headphone-B-geqvKK.jpg';
        $accMousepad = '/assets/acc-mousepad-BqJuH98_.jpg';

        // ===== LAPTOPS (22 products) =====
        $laptops = [
            [
                'slug' => 'macbook-pro-14-m1-pro-preowned',
                'name' => 'MacBook Pro 14 M1 Pro',
                'brand' => 'apple',
                'category' => 'laptops',
                'condition' => 'pre-owned',
                'price' => 132000,
                'compare_at_price' => 165000,
                'rating' => 4.4,
                'reviews_count' => 84,
                'badge' => 'Bestseller',
                'image' => $laptopPreowned,
                'cpu' => 'Apple M1 Pro 8-core',
                'ram' => '16 GB',
                'storage' => '512 GB SSD',
                'display' => '14.2" Liquid Retina XDR',
                'gpu' => null,
            ],
            [
                'slug' => 'macbook-air-m2-preowned',
                'name' => 'MacBook Air M2',
                'brand' => 'apple',
                'category' => 'laptops',
                'condition' => 'pre-owned',
                'price' => 98500,
                'compare_at_price' => 118000,
                'rating' => 4.5,
                'reviews_count' => 121,
                'badge' => 'Sale',
                'image' => $laptopPreowned,
                'cpu' => 'Apple M2 8-core',
                'ram' => '8 GB',
                'storage' => '256 GB SSD',
                'display' => '13.6" Liquid Retina',
                'gpu' => null,
            ],
            [
                'slug' => 'dell-latitude-7420-preowned',
                'name' => 'Dell Latitude 7420',
                'brand' => 'dell',
                'category' => 'laptops',
                'condition' => 'pre-owned',
                'price' => 46500,
                'compare_at_price' => null,
                'rating' => 4.6,
                'reviews_count' => 158,
                'badge' => null,
                'image' => $laptopBusiness,
                'cpu' => 'Core i5-1145G7',
                'ram' => '16 GB',
                'storage' => '512 GB NVMe',
                'display' => '14" FHD IPS',
                'gpu' => null,
            ],
            [
                'slug' => 'hp-elitebook-840-g8-preowned',
                'name' => 'HP EliteBook 840 G8',
                'brand' => 'hp',
                'category' => 'laptops',
                'condition' => 'pre-owned',
                'price' => 52000,
                'compare_at_price' => 58000,
                'rating' => 4.7,
                'reviews_count' => 195,
                'badge' => null,
                'image' => $laptopBusiness,
                'cpu' => 'Core i7-1165G7',
                'ram' => '16 GB',
                'storage' => '512 GB NVMe',
                'display' => '14" FHD',
                'gpu' => null,
            ],
            [
                'slug' => 'lenovo-thinkpad-t14-preowned',
                'name' => 'Lenovo ThinkPad T14 Gen 2',
                'brand' => 'lenovo',
                'category' => 'laptops',
                'condition' => 'pre-owned',
                'price' => 48900,
                'compare_at_price' => null,
                'rating' => 4.8,
                'reviews_count' => 232,
                'badge' => 'Bestseller',
                'image' => $laptopBusiness,
                'cpu' => 'Core i5-1135G7',
                'ram' => '16 GB',
                'storage' => '256 GB NVMe',
                'display' => '14" FHD',
                'gpu' => null,
            ],
            [
                'slug' => 'lenovo-thinkpad-x1-carbon-g9-preowned',
                'name' => 'ThinkPad X1 Carbon Gen 9',
                'brand' => 'lenovo',
                'category' => 'laptops',
                'condition' => 'pre-owned',
                'price' => 67500,
                'compare_at_price' => 76000,
                'rating' => 4.9,
                'reviews_count' => 269,
                'badge' => null,
                'image' => $laptopUltrabook,
                'cpu' => 'Core i7-1185G7',
                'ram' => '16 GB',
                'storage' => '1 TB NVMe',
                'display' => '14" WUXGA',
                'gpu' => null,
            ],
            [
                'slug' => 'dell-xps-13-9310-preowned',
                'name' => 'Dell XPS 13 9310',
                'brand' => 'dell',
                'category' => 'laptops',
                'condition' => 'pre-owned',
                'price' => 71000,
                'compare_at_price' => null,
                'rating' => 4.4,
                'reviews_count' => 306,
                'badge' => null,
                'image' => $laptopUltrabook,
                'cpu' => 'Core i7-1165G7',
                'ram' => '16 GB',
                'storage' => '512 GB NVMe',
                'display' => '13.4" FHD+ InfinityEdge',
                'gpu' => null,
            ],
            [
                'slug' => 'asus-tuf-f15-preowned',
                'name' => 'Asus TUF Gaming F15',
                'brand' => 'asus',
                'category' => 'gaming-laptops',
                'condition' => 'pre-owned',
                'price' => 79500,
                'compare_at_price' => null,
                'rating' => 4.5,
                'reviews_count' => 343,
                'badge' => null,
                'image' => $laptopGaming,
                'cpu' => 'Core i5-11400H',
                'ram' => '16 GB',
                'storage' => '512 GB NVMe',
                'display' => '15.6" 144Hz FHD',
                'gpu' => 'RTX 3050 4 GB',
            ],
            [
                'slug' => 'acer-nitro-5-preowned',
                'name' => 'Acer Nitro 5',
                'brand' => 'acer',
                'category' => 'gaming-laptops',
                'condition' => 'pre-owned',
                'price' => 72000,
                'compare_at_price' => 82000,
                'rating' => 4.6,
                'reviews_count' => 380,
                'badge' => 'Sale',
                'image' => $laptopGaming,
                'cpu' => 'Ryzen 5 5600H',
                'ram' => '16 GB',
                'storage' => '512 GB NVMe',
                'display' => '15.6" 144Hz FHD',
                'gpu' => 'GTX 1650 4 GB',
            ],
            [
                'slug' => 'hp-pavilion-15-preowned',
                'name' => 'HP Pavilion 15',
                'brand' => 'hp',
                'category' => 'laptops',
                'condition' => 'pre-owned',
                'price' => 41500,
                'compare_at_price' => null,
                'rating' => 4.7,
                'reviews_count' => 417,
                'badge' => null,
                'image' => $laptopBusiness,
                'cpu' => 'Core i5-1235U',
                'ram' => '8 GB',
                'storage' => '512 GB NVMe',
                'display' => '15.6" FHD',
                'gpu' => null,
            ],
            [
                'slug' => 'lenovo-ideapad-slim-3-preowned',
                'name' => 'Lenovo IdeaPad Slim 3',
                'brand' => 'lenovo',
                'category' => 'laptops',
                'condition' => 'pre-owned',
                'price' => 33900,
                'compare_at_price' => null,
                'rating' => 4.8,
                'reviews_count' => 454,
                'badge' => null,
                'image' => $laptopUltrabook,
                'cpu' => 'Ryzen 5 5500U',
                'ram' => '8 GB',
                'storage' => '512 GB NVMe',
                'display' => '15.6" FHD',
                'gpu' => null,
            ],
            [
                'slug' => 'dell-inspiron-3511-preowned',
                'name' => 'Dell Inspiron 15 3511',
                'brand' => 'dell',
                'category' => 'laptops',
                'condition' => 'pre-owned',
                'price' => 36500,
                'compare_at_price' => null,
                'rating' => 4.9,
                'reviews_count' => 491,
                'badge' => null,
                'image' => $laptopBusiness,
                'cpu' => 'Core i3-1115G4',
                'ram' => '8 GB',
                'storage' => '256 GB NVMe',
                'display' => '15.6" FHD',
                'gpu' => null,
            ],
            [
                'slug' => 'asus-vivobook-15-wob',
                'name' => 'Asus Vivobook 15',
                'brand' => 'asus',
                'category' => 'laptops',
                'condition' => 'without-box',
                'price' => 62900,
                'compare_at_price' => 68900,
                'rating' => 4.4,
                'reviews_count' => 528,
                'badge' => null,
                'image' => $laptopUltrabook,
                'cpu' => 'Core i5-1335U',
                'ram' => '16 GB',
                'storage' => '512 GB NVMe',
                'display' => '15.6" FHD',
                'gpu' => null,
            ],
            [
                'slug' => 'hp-victus-15-wob',
                'name' => 'HP Victus 15',
                'brand' => 'hp',
                'category' => 'gaming-laptops',
                'condition' => 'without-box',
                'price' => 104900,
                'compare_at_price' => null,
                'rating' => 4.5,
                'reviews_count' => 565,
                'badge' => 'New',
                'image' => $laptopGaming,
                'cpu' => 'Core i5-13420H',
                'ram' => '16 GB',
                'storage' => '512 GB NVMe',
                'display' => '15.6" 144Hz FHD',
                'gpu' => 'RTX 3050 6 GB',
            ],
            [
                'slug' => 'macbook-air-m3-wob',
                'name' => 'MacBook Air M3 13',
                'brand' => 'apple',
                'category' => 'laptops',
                'condition' => 'without-box',
                'price' => 148000,
                'compare_at_price' => 162000,
                'rating' => 4.6,
                'reviews_count' => 602,
                'badge' => 'Sale',
                'image' => $laptopUltrabook,
                'cpu' => 'Apple M3 8-core',
                'ram' => '8 GB',
                'storage' => '256 GB SSD',
                'display' => '13.6" Liquid Retina',
                'gpu' => null,
            ],
            [
                'slug' => 'lenovo-loq-15-wob',
                'name' => 'Lenovo LOQ 15',
                'brand' => 'lenovo',
                'category' => 'gaming-laptops',
                'condition' => 'without-box',
                'price' => 118500,
                'compare_at_price' => null,
                'rating' => 4.7,
                'reviews_count' => 639,
                'badge' => null,
                'image' => $laptopGaming,
                'cpu' => 'Core i7-13650HX',
                'ram' => '16 GB',
                'storage' => '512 GB NVMe',
                'display' => '15.6" 144Hz FHD',
                'gpu' => 'RTX 4050 6 GB',
            ],
            [
                'slug' => 'macbook-pro-14-m4-intact',
                'name' => 'MacBook Pro 14 M4',
                'brand' => 'apple',
                'category' => 'laptops',
                'condition' => 'intact',
                'price' => 214900,
                'compare_at_price' => 229000,
                'rating' => 4.8,
                'reviews_count' => 676,
                'badge' => 'Bestseller',
                'image' => $laptopUltrabook,
                'cpu' => 'Apple M4 10-core',
                'ram' => '16 GB',
                'storage' => '512 GB SSD',
                'display' => '14.2" Liquid Retina XDR',
                'gpu' => null,
            ],
            [
                'slug' => 'dell-xps-14-intact',
                'name' => 'Dell XPS 14 9440',
                'brand' => 'dell',
                'category' => 'laptops',
                'condition' => 'intact',
                'price' => 198500,
                'compare_at_price' => null,
                'rating' => 4.9,
                'reviews_count' => 713,
                'badge' => 'New',
                'image' => $laptopUltrabook,
                'cpu' => 'Core Ultra 7 155H',
                'ram' => '16 GB',
                'storage' => '1 TB NVMe',
                'display' => '14.5" FHD+ 120Hz',
                'gpu' => null,
            ],
            [
                'slug' => 'asus-rog-strix-g16-intact',
                'name' => 'Asus ROG Strix G16',
                'brand' => 'asus',
                'category' => 'gaming-laptops',
                'condition' => 'intact',
                'price' => 232000,
                'compare_at_price' => null,
                'rating' => 4.4,
                'reviews_count' => 750,
                'badge' => 'Limited',
                'image' => $laptopGaming,
                'cpu' => 'Core i7-13650HX',
                'ram' => '16 GB',
                'storage' => '1 TB NVMe',
                'display' => '16" 165Hz QHD+',
                'gpu' => 'RTX 4060 8 GB',
            ],
            [
                'slug' => 'lenovo-thinkpad-e14-g6-intact',
                'name' => 'ThinkPad E14 Gen 6',
                'brand' => 'lenovo',
                'category' => 'laptops',
                'condition' => 'intact',
                'price' => 96500,
                'compare_at_price' => null,
                'rating' => 4.5,
                'reviews_count' => 787,
                'badge' => null,
                'image' => $laptopBusiness,
                'cpu' => 'Core i5-1335U',
                'ram' => '16 GB',
                'storage' => '512 GB NVMe',
                'display' => '14" WUXGA',
                'gpu' => null,
            ],
            [
                'slug' => 'hp-probook-450-g10-intact',
                'name' => 'HP ProBook 450 G10',
                'brand' => 'hp',
                'category' => 'laptops',
                'condition' => 'intact',
                'price' => 89900,
                'compare_at_price' => 95000,
                'rating' => 4.6,
                'reviews_count' => 824,
                'badge' => null,
                'image' => $laptopBusiness,
                'cpu' => 'Core i5-1335U',
                'ram' => '8 GB',
                'storage' => '512 GB NVMe',
                'display' => '15.6" FHD',
                'gpu' => null,
            ],
            [
                'slug' => 'acer-aspire-lite-intact',
                'name' => 'Acer Aspire Lite 14',
                'brand' => 'acer',
                'category' => 'laptops',
                'condition' => 'intact',
                'price' => 58900,
                'compare_at_price' => null,
                'rating' => 4.7,
                'reviews_count' => 861,
                'badge' => null,
                'image' => $laptopUltrabook,
                'cpu' => 'Ryzen 5 5500U',
                'ram' => '16 GB',
                'storage' => '512 GB NVMe',
                'display' => '14" FHD',
                'gpu' => null,
            ],
        ];

        // ===== ACCESSORIES (12 products) =====
        $accessories = [
            [
                'slug' => 'kg-armor-laptop-backpack',
                'name' => 'Armor Laptop Backpack 15.6"',
                'brand' => 'khan-gadget',
                'category' => 'bags',
                'condition' => 'intact',
                'price' => 2650,
                'compare_at_price' => 3200,
                'rating' => 4.6,
                'reviews_count' => 214,
                'badge' => 'Bestseller',
                'image' => $accBag,
                'description' => 'Water-resistant 15.6" laptop backpack with padded sleeve, hidden anti-theft pocket and breathable back panel.',
                'highlights' => ['Fits up to 15.6"', 'Water resistant', 'USB charging port', 'Padded laptop sleeve'],
                'specs' => [['label' => 'Fits', 'value' => 'Up to 15.6 inch'], ['label' => 'Material', 'value' => 'Water-resistant polyester'], ['label' => 'Capacity', 'value' => '28 L'], ['label' => 'Warranty', 'value' => '6 months']],
            ],
            [
                'slug' => 'kg-slim-laptop-sleeve',
                'name' => 'Slim Laptop Sleeve 14"',
                'brand' => 'khan-gadget',
                'category' => 'bags',
                'condition' => 'intact',
                'price' => 1150,
                'compare_at_price' => null,
                'rating' => 4.4,
                'reviews_count' => 96,
                'badge' => null,
                'image' => $accBag,
                'description' => 'Shock-absorbing sleeve with soft inner lining, keeps your ultrabook safe inside any bag.',
                'highlights' => ['Fits 13–14 inch', 'Shock absorbing foam', 'Soft inner lining', 'Slim profile'],
                'specs' => [['label' => 'Fits', 'value' => '13 – 14 inch'], ['label' => 'Material', 'value' => 'Neoprene'], ['label' => 'Closure', 'value' => 'YKK zipper'], ['label' => 'Warranty', 'value' => '3 months']],
            ],
            [
                'slug' => 'silent-wireless-mouse-w300',
                'name' => 'Silent Wireless Mouse W300',
                'brand' => 'khan-gadget',
                'category' => 'mouse',
                'condition' => 'intact',
                'price' => 890,
                'compare_at_price' => 1200,
                'rating' => 4.5,
                'reviews_count' => 312,
                'badge' => 'Sale',
                'image' => $accMouse,
                'description' => '2.4 GHz silent-click wireless mouse with 1600 DPI optical sensor and 12-month battery life.',
                'highlights' => ['Silent clicks', '1600 DPI', '2.4 GHz USB receiver', '12-month battery'],
                'specs' => [['label' => 'Connection', 'value' => '2.4 GHz wireless'], ['label' => 'DPI', 'value' => '800 / 1200 / 1600'], ['label' => 'Battery', 'value' => '1× AA'], ['label' => 'Warranty', 'value' => '1 year']],
            ],
            [
                'slug' => 'rgb-gaming-mouse-gx7',
                'name' => 'RGB Gaming Mouse GX7',
                'brand' => 'khan-gadget',
                'category' => 'mouse',
                'condition' => 'intact',
                'price' => 1450,
                'compare_at_price' => null,
                'rating' => 4.6,
                'reviews_count' => 148,
                'badge' => null,
                'image' => $accMouse,
                'description' => '7-button RGB gaming mouse with adjustable 7200 DPI sensor and braided cable.',
                'highlights' => ['7200 DPI', '7 programmable buttons', 'RGB lighting', 'Braided cable'],
                'specs' => [['label' => 'Sensor', 'value' => 'Optical 7200 DPI'], ['label' => 'Buttons', 'value' => '7 programmable'], ['label' => 'Cable', 'value' => '1.8 m braided'], ['label' => 'Warranty', 'value' => '1 year']],
            ],
            [
                'slug' => 'mechanical-keyboard-tkl-blue',
                'name' => 'Mechanical Keyboard TKL',
                'brand' => 'khan-gadget',
                'category' => 'keyboard',
                'condition' => 'intact',
                'price' => 3450,
                'compare_at_price' => 3990,
                'rating' => 4.7,
                'reviews_count' => 187,
                'badge' => 'Bestseller',
                'image' => $accKeyboard,
                'description' => 'Tenkeyless mechanical keyboard with blue switches, double-shot keycaps and white backlight.',
                'highlights' => ['Blue mechanical switches', '87-key TKL', 'Double-shot keycaps', 'Detachable USB-C'],
                'specs' => [['label' => 'Layout', 'value' => '87-key TKL'], ['label' => 'Switch', 'value' => 'Blue tactile clicky'], ['label' => 'Backlight', 'value' => 'White LED'], ['label' => 'Warranty', 'value' => '1 year']],
            ],
            [
                'slug' => 'wireless-keyboard-mouse-combo',
                'name' => 'Wireless Keyboard + Mouse Combo',
                'brand' => 'khan-gadget',
                'category' => 'keyboard',
                'condition' => 'intact',
                'price' => 1990,
                'compare_at_price' => null,
                'rating' => 4.4,
                'reviews_count' => 121,
                'badge' => null,
                'image' => $accKeyboard,
                'description' => 'Full-size wireless keyboard and mouse combo on a single nano receiver — ideal for laptop desk setups.',
                'highlights' => ['Single nano receiver', 'Full-size layout', 'Spill resistant', 'Plug & play'],
                'specs' => [['label' => 'Connection', 'value' => '2.4 GHz wireless'], ['label' => 'Layout', 'value' => '104-key full size'], ['label' => 'Battery', 'value' => 'AA × 3'], ['label' => 'Warranty', 'value' => '1 year']],
            ],
            [
                'slug' => 'ddr4-8gb-3200-laptop-ram',
                'name' => 'DDR4 8GB 3200MHz Laptop RAM',
                'brand' => 'khan-gadget',
                'category' => 'ram',
                'condition' => 'intact',
                'price' => 2450,
                'compare_at_price' => null,
                'rating' => 4.8,
                'reviews_count' => 264,
                'badge' => 'Bestseller',
                'image' => $accRam,
                'description' => 'SODIMM DDR4 8GB 3200MHz module — the fastest, cheapest way to make an older laptop feel new again.',
                'highlights' => ['8 GB SODIMM', '3200 MHz', '1.2 V low power', 'Lifetime warranty'],
                'specs' => [['label' => 'Capacity', 'value' => '8 GB'], ['label' => 'Type', 'value' => 'DDR4 SODIMM'], ['label' => 'Speed', 'value' => '3200 MHz'], ['label' => 'Warranty', 'value' => 'Lifetime']],
            ],
            [
                'slug' => 'ddr4-16gb-3200-laptop-ram',
                'name' => 'DDR4 16GB 3200MHz Laptop RAM',
                'brand' => 'khan-gadget',
                'category' => 'ram',
                'condition' => 'intact',
                'price' => 4390,
                'compare_at_price' => 4990,
                'rating' => 4.8,
                'reviews_count' => 173,
                'badge' => 'Sale',
                'image' => $accRam,
                'description' => '16GB SODIMM module for heavy multitasking, editing and virtual machines on any modern laptop.',
                'highlights' => ['16 GB SODIMM', '3200 MHz', 'Free installation', 'Lifetime warranty'],
                'specs' => [['label' => 'Capacity', 'value' => '16 GB'], ['label' => 'Type', 'value' => 'DDR4 SODIMM'], ['label' => 'Speed', 'value' => '3200 MHz'], ['label' => 'Warranty', 'value' => 'Lifetime']],
            ],
            [
                'slug' => 'anc-over-ear-headphone-h9',
                'name' => 'ANC Over-Ear Headphone H9',
                'brand' => 'khan-gadget',
                'category' => 'headphones',
                'condition' => 'intact',
                'price' => 4890,
                'compare_at_price' => 5900,
                'rating' => 4.6,
                'reviews_count' => 208,
                'badge' => 'New',
                'image' => $accHeadphone,
                'description' => 'Active noise cancelling over-ear headphone with 40mm drivers, 40-hour battery and a built-in mic for meetings.',
                'highlights' => ['Active noise cancelling', '40 hr battery', '40 mm drivers', 'Built-in mic'],
                'specs' => [['label' => 'Drivers', 'value' => '40 mm'], ['label' => 'Battery', 'value' => '40 hours'], ['label' => 'Connection', 'value' => 'Bluetooth 5.3 + AUX'], ['label' => 'Warranty', 'value' => '1 year']],
            ],
            [
                'slug' => 'usb-headphone-with-mic-office',
                'name' => 'USB Office Headset with Mic',
                'brand' => 'khan-gadget',
                'category' => 'headphones',
                'condition' => 'intact',
                'price' => 1690,
                'compare_at_price' => null,
                'rating' => 4.3,
                'reviews_count' => 87,
                'badge' => null,
                'image' => $accHeadphone,
                'description' => 'USB wired headset with noise-cancelling boom mic — built for calls, classes and support desks.',
                'highlights' => ['Noise cancelling mic', 'USB plug & play', 'Padded ear cups', 'In-line controls'],
                'specs' => [['label' => 'Connection', 'value' => 'USB-A wired'], ['label' => 'Mic', 'value' => 'Noise cancelling boom'], ['label' => 'Cable', 'value' => '2 m'], ['label' => 'Warranty', 'value' => '6 months']],
            ],
            [
                'slug' => 'xl-desk-mousepad-900',
                'name' => 'XL Desk Mousepad 900×400',
                'brand' => 'khan-gadget',
                'category' => 'mousepad',
                'condition' => 'intact',
                'price' => 950,
                'compare_at_price' => null,
                'rating' => 4.7,
                'reviews_count' => 302,
                'badge' => 'Bestseller',
                'image' => $accMousepad,
                'description' => 'Extended 900×400 mm desk mat with stitched edges and anti-slip rubber base — covers keyboard and mouse.',
                'highlights' => ['900 × 400 mm', 'Stitched edge', 'Anti-slip base', 'Washable'],
                'specs' => [['label' => 'Size', 'value' => '900 × 400 mm'], ['label' => 'Thickness', 'value' => '3 mm'], ['label' => 'Base', 'value' => 'Natural rubber'], ['label' => 'Surface', 'value' => 'Micro-weave cloth']],
            ],
            [
                'slug' => 'rgb-gaming-mousepad-led',
                'name' => 'RGB Gaming Mousepad',
                'brand' => 'khan-gadget',
                'category' => 'mousepad',
                'condition' => 'intact',
                'price' => 1290,
                'compare_at_price' => 1590,
                'rating' => 4.5,
                'reviews_count' => 134,
                'badge' => null,
                'image' => $accMousepad,
                'description' => 'LED-lit gaming mousepad with 14 lighting modes and a smooth low-friction surface.',
                'highlights' => ['14 RGB modes', '800 × 300 mm', 'USB powered', 'Anti-slip base'],
                'specs' => [['label' => 'Size', 'value' => '800 × 300 mm'], ['label' => 'Lighting', 'value' => '14 modes'], ['label' => 'Power', 'value' => 'USB-A'], ['label' => 'Warranty', 'value' => '6 months']],
            ],
        ];

        $conditionDescriptions = [
            'pre-owned' => ' — certified pre-owned, fully tested and graded by our engineers. Battery health and cosmetic grade are listed on the invoice, with service warranty from Khan Gadget.',
            'without-box' => ' — brand new machine, original retail box unavailable. Full accessories included and covered by official warranty.',
            'intact' => ' — brand new, factory sealed intact box with full official warranty and complete accessories.',
        ];

        // Seed laptops
        foreach ($laptops as $i => $data) {
            $condSlug = $data['condition'];
            $description = $data['name'] . ($conditionDescriptions[$condSlug] ?? '');

            $product = Product::create([
                'slug' => $data['slug'],
                'name' => $data['name'],
                'brand_id' => $brands[$data['brand']],
                'category_id' => $categories[$data['category']],
                'condition_id' => $conditions[$data['condition']],
                'price' => $data['price'],
                'compare_at_price' => $data['compare_at_price'],
                'rating' => $data['rating'],
                'reviews_count' => $data['reviews_count'],
                'badge' => $data['badge'],
                'description' => $description,
                'in_stock' => true,
            ]);

            // Image
            $product->images()->create(['image_path' => $data['image'], 'is_primary' => true, 'sort_order' => 0]);

            // Highlights
            $highlights = [$data['cpu'], $data['ram'] . ' RAM', $data['storage']];
            if ($data['gpu']) {
                $highlights[] = $data['gpu'];
            } else {
                $highlights[] = $data['display'];
            }
            foreach ($highlights as $j => $h) {
                $product->highlights()->create(['text' => $h, 'sort_order' => $j]);
            }

            // Specs
            $specs = [
                ['label' => 'Processor', 'value' => $data['cpu']],
                ['label' => 'Memory', 'value' => $data['ram']],
                ['label' => 'Storage', 'value' => $data['storage']],
                ['label' => 'Display', 'value' => $data['display']],
            ];
            if ($data['gpu']) {
                $specs[] = ['label' => 'Graphics', 'value' => $data['gpu']];
            }
            $specs[] = ['label' => 'Condition', 'value' => strtoupper(str_replace('-', ' ', $condSlug === 'without-box' ? 'BRAND NEW WITHOUT BOX' : ($condSlug === 'intact' ? 'BRAND NEW INTACT BOX' : 'PRE-OWNED')))];

            foreach ($specs as $j => $s) {
                $product->specs()->create(['label' => $s['label'], 'value' => $s['value'], 'sort_order' => $j]);
            }

            // Colors (all laptops get the same 2 colors)
            $product->colors()->createMany([
                ['hex_code' => '#1d1d1f', 'name' => 'Space Black'],
                ['hex_code' => '#c8c8cc', 'name' => 'Silver'],
            ]);
        }

        // Seed accessories
        foreach ($accessories as $data) {
            $product = Product::create([
                'slug' => $data['slug'],
                'name' => $data['name'],
                'brand_id' => $brands[$data['brand']],
                'category_id' => $categories[$data['category']],
                'condition_id' => $conditions[$data['condition']],
                'price' => $data['price'],
                'compare_at_price' => $data['compare_at_price'] ?? null,
                'rating' => $data['rating'],
                'reviews_count' => $data['reviews_count'],
                'badge' => $data['badge'] ?? null,
                'description' => $data['description'],
                'in_stock' => true,
            ]);

            $product->images()->create(['image_path' => $data['image'], 'is_primary' => true, 'sort_order' => 0]);

            foreach ($data['highlights'] as $j => $h) {
                $product->highlights()->create(['text' => $h, 'sort_order' => $j]);
            }

            foreach ($data['specs'] as $j => $s) {
                $product->specs()->create(['label' => $s['label'], 'value' => $s['value'], 'sort_order' => $j]);
            }
        }
    }
}
